# Generated by Django 2.1.4 on 2018-12-12 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesee',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('semaine', models.IntegerField()),
                ('poids_min', models.IntegerField()),
                ('poids_max', models.IntegerField()),
                ('tare', models.IntegerField()),
                ('dateDebut', models.DateField(default=datetime.datetime(2018, 12, 12, 22, 35, 34, 237484, tzinfo=utc))),
                ('dateFin', models.DateField()),
            ],
        ),
    ]
