# Generated by Django 2.1.4 on 2018-12-12 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesee',
            name='dateDebut',
        ),
        migrations.RemoveField(
            model_name='pesee',
            name='dateFin',
        ),
        migrations.AddField(
            model_name='pesee',
            name='chemin_acces',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pesee',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 22, 43, 10, 562674, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='pesee',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pesee',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
