# Generated by Django 2.1.4 on 2018-12-27 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181226_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesee',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2018, 12, 27, 11, 11, 54, 600429, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pesee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
