# Generated by Django 2.1.4 on 2018-12-27 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181227_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesee',
            name='chemin_acces',
        ),
        migrations.AddField(
            model_name='pesee',
            name='fichier',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d %H:%M:%S.csv'),
        ),
        migrations.AlterField(
            model_name='pesee',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2018, 12, 27, 18, 37, 6, 649249, tzinfo=utc)),
        ),
    ]
