# Generated by Django 2.1.4 on 2018-12-27 23:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181227_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesee',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 23, 10, 17, 27050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pesee',
            name='date_fin',
            field=models.DateTimeField(null=True),
        ),
    ]
