# Generated by Django 2.1.4 on 2018-12-28 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20181227_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesee',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 10, 57, 45, 372859, tzinfo=utc)),
        ),
    ]
