# Generated by Django 2.1.4 on 2018-12-28 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20181228_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesee',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 13, 30, 27, 838690)),
        ),
    ]
