# Generated by Django 2.1.7 on 2019-02-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190213_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesee',
            name='fichier',
        ),
    ]
