# Generated by Django 2.1.7 on 2019-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_pesee_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
