# Generated by Django 2.1.4 on 2018-12-12 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poids',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 22, 43, 10, 564673, tzinfo=utc)),
        ),
    ]
