# Generated by Django 2.1.4 on 2018-12-12 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181212_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poids',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 22, 54, 40, 221523, tzinfo=utc)),
        ),
    ]
