# Generated by Django 2.1.4 on 2018-12-27 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20181226_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poids',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 27, 11, 11, 54, 601417, tzinfo=utc)),
        ),
    ]
