# Generated by Django 2.1.4 on 2018-12-27 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181227_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poids',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 27, 18, 37, 6, 648918, tzinfo=utc)),
        ),
    ]
