# Generated by Django 2.1.7 on 2019-02-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_poids_pesee_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poids',
        ),
    ]
